# Homework Assigment No.1
# Harsh Thakur
# IS664 Database Programming
#
SET @A=10;
SET @B=15;
SET @C=20;
SET @D=25;
SET @E=27.8;
SET @S1="Welcome to Database Programming";
SET @S2="IS664 MySQL RDBMS Programming Course";
SET @D1=cast('2017-01-01' as DATE);
SET @D2=cast('2017-12-21' as DATE);
SELECT @A,@B,@C,@D,@E,@S1,@S2,@D1,@D2 AS TASK1;
SET @F=CHAR_LENGTH(@S1); # Used an additional variable to store the numeric length of the string
SELECT cos(@F) AS TASK2;
SELECT DATEDIFF(@D2,@D1) AS TASK3;
SELECT "The Sum of A,B,C,and D is: Total of A,B,C and D" AS TASK4;
# Number of Radians in a circle = 2 *(PI())
SELECT TAN(SQRT(2*PI())) AS TASK5;
SELECT MOD(SQRT(PI()),2) AS TASK6;
SELECT CHAR(@E) AS TASK7;
SELECT IF(ASIN(@C)=NULL, "YES","NO") AS TASK8;
SELECT DATE_ADD(@D1, INTERVAL 6 MONTH) + INTERVAL 3 DAY AS TASK9;
SELECT DATE_FORMAT(@D1,"%W %D %M %Y") AS TASK10;
SELECT DAYOFWEEK(@D1)*DAYOFWEEK(@D2) AS TASK11;
SELECT IF(INSTR(@S1,'e'),'YES','NO') AS TASK12;
SELECT CASE @S1 WHEN SUBSTRING(@S1,1,3)='l' THEN "3-YES" ELSE "3-NO" END AS "TASK13";
SELECT CASE @S1 WHEN SUBSTRING(@S1,29,3)='el'||'se' || 'ng' THEN "PATTERN FOUND" ELSE "PATTERN NOT FOUND" END AS "TASK14";
SELECT CASE @S2 WHEN SUBSTRING(@S2,1,8)="66" && SUBSTRING(@S2,24,12)='mm' THEN "CONTAINS 2" ELSE "DOES NOT CONTAIN 2" END AS "TASK15";